In [1]:
import torch

X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
Y = torch.tensor([[0], [1], [1], [1]], dtype=torch.float)


w = torch.randn(2, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print("before update")
print(w)
print(b)

lr = 0.1
epochs = 10000

#perceptron
for epoch in range(epochs):
    # Forward pass
    y_pred = torch.matmul(X, w) + b
    # loss
    loss = ((y_pred - Y)**2).mean()
    # Backward pass
    loss.backward()
    # Update weights and bias
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        # Reset gradients
        w.grad.zero_()
        b.grad.zero_()

# Test the perceptron
test_input = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
test_output = torch.matmul(test_input, w) + b
print(test_output.round())


C:\Users\hizzu\AppData\Local\Temp\ipykernel_18984\3615496743.py:3: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:77.)
  X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)


before update
tensor([[ 1.3707],
        [-0.6386]], requires_grad=True)
tensor([0.2361], requires_grad=True)
tensor([[0.],
        [1.],
        [1.],
        [1.]], grad_fn=<RoundBackward0>)


In [2]:
print("after update")
print(w)
print(b)

after update
tensor([[0.5000],
        [0.5000]], requires_grad=True)
tensor([0.2500], requires_grad=True)
